####markItUp;0.0.1_alpha;Murat Purc;markItUp####

# --------------------------------------------------------
#
# new type entries
#
INSERT INTO !PREFIX!_type VALUES ('!PID!00', 'CMS_MIUMARKDOWN', '/**\r\n * Contenido CMS-Type CMS_MIUMARKDOWN\r\n *\r\n * @author      Murat Purc <murat@purc.de>\r\n * @copyright   © Murat Purc 2008\r\n * @date        03.10.2008\r\n * @package     Contenido\r\n * @subpackage  matkItUp\r\n */\r\n\r\n\r\n// define the CMS-Type\r\n$currentMarkupCmsType = ''CMS_MIUMARKDOWN'';\r\n\r\n// use include() statement to provide access to all variables in global scope\r\n$pluginPath = $cfg[''path''][''contenido''] . $cfg[''path''][''plugins''] . ''markitup/'';\r\ninclude ($pluginPath . ''includes/markup_inside_editing_area.php'');\r\n\r\n// reset \r\nunset($pluginPath, $currentMarkupCmsType);', 'Markup / Markdown', 0, '', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO !PREFIX!_type VALUES ('!PID!01', 'CMS_MIUTEXTILE', '/**\r\n * Contenido CMS-Type CMS_MIUTEXTILE\r\n *\r\n * @author      Murat Purc <murat@purc.de>\r\n * @copyright   © Murat Purc 2008\r\n * @date        03.10.2008\r\n * @package     Contenido\r\n * @subpackage  matkItUp\r\n */\r\n\r\n// define the CMS-Type\r\n$currentMarkupCmsType = ''CMS_MIUTEXTILE'';\r\n\r\n// use include() statement to provide access to all variables in global scope\r\n$pluginPath = $cfg[''path''][''contenido''] . $cfg[''path''][''plugins''] . ''markitup/'';\r\ninclude ($pluginPath . ''includes/markup_inside_editing_area.php'');\r\n\r\n// reset \r\nunset($pluginPath, $currentMarkupCmsType);', 'Markup / Textile', 0, '', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO !PREFIX!_type VALUES ('!PID!02', 'CMS_MIUBBCODE', '/**\r\n * Contenido CMS-Type CMS_MIUBBCODE\r\n *\r\n * @author      Murat Purc <murat@purc.de>\r\n * @copyright   © Murat Purc 2008\r\n * @date        03.10.2008\r\n * @package     Contenido\r\n * @subpackage  matkItUp\r\n */\r\n\r\n// define the CMS-Type\r\n$currentMarkupCmsType = ''CMS_MIUBBCODE'';\r\n\r\n// use include() statement to provide access to all variables in global scope\r\n$pluginPath = $cfg[''path''][''contenido''] . $cfg[''path''][''plugins''] . ''markitup/'';\r\ninclude ($pluginPath . ''includes/markup_inside_editing_area.php'');\r\n\r\n// reset \r\nunset($pluginPath, $currentMarkupCmsType);', 'Markup / BBCode', 0, '', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO !PREFIX!_type VALUES ('!PID!03', 'CMS_MIUTEXY', '/**\r\n * Contenido CMS-Type CMS_MIUTEXY\r\n *\r\n * @author      Murat Purc <murat@purc.de>\r\n * @copyright   © Murat Purc 2008\r\n * @date        03.10.2008\r\n * @package     Contenido\r\n * @subpackage  matkItUp\r\n */\r\n\r\n// define the CMS-Type\r\n$currentMarkupCmsType = ''CMS_MIUTEXY'';\r\n\r\n// use include() statement to provide access to all variables in global scope\r\n$pluginPath = $cfg[''path''][''contenido''] . $cfg[''path''][''plugins''] . ''markitup/'';\r\ninclude ($pluginPath . ''includes/markup_inside_editing_area.php'');\r\n\r\n// reset \r\nunset($pluginPath, $currentMarkupCmsType);', 'Markup / Texy', 0, '', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO !PREFIX!_type VALUES ('!PID!04', 'CMS_MIUWIKI', '/**\r\n * Contenido CMS-Type CMS_MIUWIKI\r\n *\r\n * @author      Murat Purc <murat@purc.de>\r\n * @copyright   © Murat Purc 2008\r\n * @date        03.10.2008\r\n * @package     Contenido\r\n * @subpackage  matkItUp\r\n */\r\n\r\n// define the CMS-Type\r\n$currentMarkupCmsType = ''CMS_MIUWIKI'';\r\n\r\n// use include() statement to provide access to all variables in global scope\r\n$pluginPath = $cfg[''path''][''contenido''] . $cfg[''path''][''plugins''] . ''markitup/'';\r\ninclude ($pluginPath . ''includes/markup_inside_editing_area.php'');\r\n\r\n// reset \r\nunset($pluginPath, $currentMarkupCmsType);', 'Markup / Wiki', 0, '', '0000-00-00 00:00:00', '0000-00-00 00:00:00');

