####markItUp;0.1;Murat Purc;markItUp####

# --------------------------------------------------------
#
# new type entries
#
INSERT INTO !PREFIX!_type VALUES ('!PID!00', 'CMS_MIUMARKDOWN', '/**\n * CONTENIDO CMS-Type CMS_MIUMARKDOWN\n *\n * @author      Murat Purc <murat@purc.de>\n * @copyright   Copyright (c) 2008-2011 Murat Purc (http://www.purc.de)\n * @date        03.10.2008\n * @package     CONTENIDO\n * @subpackage  matkItUp\n */\n\n\n// define the CMS-Type\n$currentMarkupCmsType = ''CMS_MIUMARKDOWN'';\n\n// use include() statement to provide access to all variables in global scope\n$pluginPath = $cfg[''path''][''contenido''] . $cfg[''path''][''plugins''] . ''markitup/'';\ninclude ($pluginPath . ''includes/markup_inside_editing_area.php'');\n\n// reset \nunset($pluginPath, $currentMarkupCmsType);', 'Markup / Markdown', 0, '', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO !PREFIX!_type VALUES ('!PID!01', 'CMS_MIUTEXTILE', '/**\n * CONTENIDO CMS-Type CMS_MIUTEXTILE\n *\n * @author      Murat Purc <murat@purc.de>\n * @copyright   Copyright (c) 2008-2011 Murat Purc (http://www.purc.de)\n * @date        03.10.2008\n * @package     CONTENIDO\n * @subpackage  matkItUp\n */\n\n// define the CMS-Type\n$currentMarkupCmsType = ''CMS_MIUTEXTILE'';\n\n// use include() statement to provide access to all variables in global scope\n$pluginPath = $cfg[''path''][''contenido''] . $cfg[''path''][''plugins''] . ''markitup/'';\ninclude ($pluginPath . ''includes/markup_inside_editing_area.php'');\n\n// reset \nunset($pluginPath, $currentMarkupCmsType);', 'Markup / Textile', 0, '', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO !PREFIX!_type VALUES ('!PID!02', 'CMS_MIUBBCODE', '/**\n * CONTENIDO CMS-Type CMS_MIUBBCODE\n *\n * @author      Murat Purc <murat@purc.de>\n * @copyright   Copyright (c) 2008-2011 Murat Purc (http://www.purc.de)\n * @date        03.10.2008\n * @package     CONTENIDO\n * @subpackage  matkItUp\n */\n\n// define the CMS-Type\n$currentMarkupCmsType = ''CMS_MIUBBCODE'';\n\n// use include() statement to provide access to all variables in global scope\n$pluginPath = $cfg[''path''][''contenido''] . $cfg[''path''][''plugins''] . ''markitup/'';\ninclude ($pluginPath . ''includes/markup_inside_editing_area.php'');\n\n// reset \nunset($pluginPath, $currentMarkupCmsType);', 'Markup / BBCode', 0, '', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO !PREFIX!_type VALUES ('!PID!03', 'CMS_MIUTEXY', '/**\n * CONTENIDO CMS-Type CMS_MIUTEXY\n *\n * @author      Murat Purc <murat@purc.de>\n * @copyright   Copyright (c) 2008-2011 Murat Purc (http://www.purc.de)\n * @date        03.10.2008\n * @package     CONTENIDO\n * @subpackage  matkItUp\n */\n\n// define the CMS-Type\n$currentMarkupCmsType = ''CMS_MIUTEXY'';\n\n// use include() statement to provide access to all variables in global scope\n$pluginPath = $cfg[''path''][''contenido''] . $cfg[''path''][''plugins''] . ''markitup/'';\ninclude ($pluginPath . ''includes/markup_inside_editing_area.php'');\n\n// reset \nunset($pluginPath, $currentMarkupCmsType);', 'Markup / Texy', 0, '', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO !PREFIX!_type VALUES ('!PID!04', 'CMS_MIUWIKI', '/**\n * CONTENIDO CMS-Type CMS_MIUWIKI\n *\n * @author      Murat Purc <murat@purc.de>\n * @copyright   Copyright (c) 2008-2011 Murat Purc (http://www.purc.de)\n * @date        03.10.2008\n * @package     CONTENIDO\n * @subpackage  matkItUp\n */\n\n// define the CMS-Type\n$currentMarkupCmsType = ''CMS_MIUWIKI'';\n\n// use include() statement to provide access to all variables in global scope\n$pluginPath = $cfg[''path''][''contenido''] . $cfg[''path''][''plugins''] . ''markitup/'';\ninclude ($pluginPath . ''includes/markup_inside_editing_area.php'');\n\n// reset \nunset($pluginPath, $currentMarkupCmsType);', 'Markup / Wiki', 0, '', '0000-00-00 00:00:00', '0000-00-00 00:00:00');

